Update SmartBear.yml

diff --git a/.github/workflows/SmartBear.yml b/.github/workflows/SmartBear.yml
--- a/.github/workflows/SmartBear.yml
+++ b/.github/workflows/SmartBear.yml
@@ -9,29 +9,30 @@ jobs:
     steps:
       - name: Check out the repository
         uses: actions/checkout@v4
-      - name: My Docker Build Action_181992
-        uses: Praveen-1992/my-docker-app@v5
-     # Step 3: Log in to Docker Hub
+
+      # Step 2: Log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}  
         
-       # Step 4: Build the Docker image
+      # Step 3: Build the Docker image
       - name: Build Docker image
         run: |
           docker build -t my-docker-app:latest .  
 
-      # Step 5: Push the Docker image to Docker Hub
-      - name: Push Docker image
-        run: |
-          docker tag my-docker-app:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest 
-
-      # Step 6: Run the Docker image
+      # Step 4: Run Docker container
       - name: Run Docker container
         run: |
-          docker run -d --name my-running-app my-docker-app:latestt    
-     
-      
+          docker run --name my-running-app -d my-docker-app:latest
+
+      # Optional Step 5: Check logs to confirm entrypoint execution
+      - name: Check logs
+        run: |
+          docker logs my-running-app
+          
+      # Optional Step 6: Cleanup
+      - name: Cleanup
+        run: |
+          docker rm -f my-running-app || true
